# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x08LogEntry\x12\x0c\n\x04Term\x18\x01 \x01(\x03\x12\x0b\n\x03Msg\x18\x02 \x01(\t\"Q\n\x0bVoteRequest\x12\x10\n\x08\x46romNode\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x03\x12\x11\n\tLogLength\x18\x03 \x01(\x03\x12\x0f\n\x07LogTerm\x18\x04 \x01(\x03\"?\n\x0cVoteResponse\x12\x10\n\x08\x46romNode\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x03\x12\x0f\n\x07Granted\x18\x03 \x01(\x08\"\x87\x01\n\nLogRequest\x12\x10\n\x08LeaderId\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x03\x12\x11\n\tLogLength\x18\x03 \x01(\x03\x12\x0f\n\x07LogTerm\x18\x04 \x01(\x03\x12\x14\n\x0cLeaderCommit\x18\x05 \x01(\x03\x12\x1f\n\x07\x45ntries\x18\x06 \x03(\x0b\x32\x0e.raft.LogEntry\"K\n\x0bLogResponse\x12\x10\n\x08\x46ollower\x18\x01 \x01(\t\x12\x0c\n\x04Term\x18\x02 \x01(\x03\x12\x0b\n\x03\x41\x63k\x18\x03 \x01(\x03\x12\x0f\n\x07Success\x18\x04 \x01(\x08\x32\xfe\x01\n\x04Raft\x12<\n\x0fSendVoteRequest\x12\x11.raft.VoteRequest\x1a\x16.google.protobuf.Empty\x12>\n\x10SendVoteResponse\x12\x12.raft.VoteResponse\x1a\x16.google.protobuf.Empty\x12:\n\x0eSendLogRequest\x12\x10.raft.LogRequest\x1a\x16.google.protobuf.Empty\x12<\n\x0fSendLogResponse\x12\x11.raft.LogResponse\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=49
  _globals['_LOGENTRY']._serialized_end=86
  _globals['_VOTEREQUEST']._serialized_start=88
  _globals['_VOTEREQUEST']._serialized_end=169
  _globals['_VOTERESPONSE']._serialized_start=171
  _globals['_VOTERESPONSE']._serialized_end=234
  _globals['_LOGREQUEST']._serialized_start=237
  _globals['_LOGREQUEST']._serialized_end=372
  _globals['_LOGRESPONSE']._serialized_start=374
  _globals['_LOGRESPONSE']._serialized_end=449
  _globals['_RAFT']._serialized_start=452
  _globals['_RAFT']._serialized_end=706
# @@protoc_insertion_point(module_scope)
